version: '3'
services:
  backend:
    image: python:3.11
    volumes:
      - ./backend:/app
      - ./schema:/app/schema
      - ./tmp/backend.ini:/backend.ini
    working_dir: /app
    command: bash -c "pip install -r v1/requirements.txt && python v1/server.py"
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      GIT_COMMIT_INFO: 'Commit messages are not available locally'
      GIT_COMMIT_HASH: ''
      LOGINM_SEED: ${LOGINM_SEED}
      LOGINB_SEED: ${LOGINB_SEED}
      EVENT_API_TOKEN: ${EVENT_API_TOKEN}
      SECRET_KEY: "SECRET_KEY" # Change this to a random string

  mongo:
    image: mongo:latest
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8082:8081"
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

volumes:
  mongodata:
