version: '3'
services:
  backend:
    image: python:3.11
    volumes:
      - ./backend:/app  # Mount the backend code
      - ./schema:/app/schema  # Mount the schema directory
      - ./tmp/backend.ini:/app/backend.ini
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python server.py"
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    

  mongo:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:
