version: '3'
services:
  backend:
    image: python:3.11
    volumes:
      - ./backend:/app
      - ./schema:/app/schema
      - ${PWD}/tmp/backend.ini:/backend.ini
      - ${PWD}/fastlane/metadata/review_information/demo_user.txt:/review_user.txt
      - ${PWD}/fastlane/metadata/review_information/demo_password.txt:/review_password.txt
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && python server.py"
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      GIT_COMMIT_INFO: 'Commit messages are not available locally'
      GIT_COMMIT_HASH: ''

  mongo:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:
