version: '3'
services:
  website:
    image: ghcr.io/skaramicke/swagapp/website:latest
    ports:
      - "8080:80"

  backend:
    image: ghcr.io/skaramicke/swagapp/backend:latest
    depends_on:
      - mongo
    volumes:
      - ${PWD}/fastlane/metadata/review_information/demo_user.txt:/review_user.txt
      - /persistent/review_password.txt:/review_password.txt
      - /persistent/backend.ini:/backend.ini

  mongo:
    image: mongo:latest
    volumes:
      - /persistent/mongo:/data/db

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    restart: unless-stopped
    env_file:
      - fileName: /persistent/mongo-express.env

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    environment:
      - WATCHTOWER_CLEANUP=true
