version: '3'
services:
  website:
    image: ghcr.io/skaramicke/swagapp/website:latest
    ports:
      - "8080:80"

  backend:
    image: ghcr.io/skaramicke/swagapp/backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - /persistent/.env:/app/.env

  mongo:
    image: mongo:latest
    volumes:
      - /persistent/mongo:/data/db
    ports:
      - "27017:27017"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    environment:
      - WATCHTOWER_CLEANUP=true
