/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface User {
  id?: string;
  username?: string;
  name?: string;
  age?: number;
  slogan?: string;
  avatar_url?: string;
  location?: {
    latitude?: number;
    longitude?: number;
    timestamp?: number;
    [k: string]: unknown;
  };
  show_location?: boolean;
  [k: string]: unknown;
}
