/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/v1/authm": {
    /** Authm */
    post: operations["authm_v1_authm_post"];
  };
  "/v1/authb": {
    /** Authb */
    post: operations["authb_v1_authb_post"];
  };
  "/v1/health": {
    /** Health */
    get: operations["health_v1_health_get"];
  };
  "/v1/users_showing_location": {
    /** Users Showing Location */
    get: operations["users_showing_location_v1_users_showing_location_get"];
  };
  "/v1/users/me/": {
    /** Read Users Me */
    get: operations["read_users_me_v1_users_me__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** AuthRequest */
    AuthRequest: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** AuthResponse */
    AuthResponse: {
      /** Accesstoken */
      accessToken: string;
      /** Refreshtoken */
      refreshToken: string;
      user: components["schemas"]["User"];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** User */
    User: {
      /**
       * Userid
       * @example 123
       */
      userId: number;
      /**
       * Ismember
       * @default false
       * @example true
       */
      isMember?: boolean;
      /**
       * Show Location
       * @default false
       * @example true
       */
      show_location?: boolean;
      /**
       * Show Contact Info
       * @default false
       * @example true
       */
      show_contact_info?: boolean;
      /**
       * Age
       * @example 30
       */
      age?: number | null;
      /**
       * Slogan
       * @example Live and Let Live
       */
      slogan?: string | null;
      /**
       * Avatar Url
       * @example https://example.com/avatar.jpg
       */
      avatar_url?: string | null;
      /**
       * Firstname
       * @example John Doe
       */
      firstName?: string | null;
      /**
       * Lastname
       * @example John Doe
       */
      lastName?: string | null;
      /**
       * Email
       * @example johndoe@example.com
       */
      email?: string | null;
      /**
       * Phone
       * @example +1234567890
       */
      phone?: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Authm */
  authm_v1_authm_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AuthResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Authb */
  authb_v1_authb_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /** Health */
  health_v1_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Users Showing Location */
  users_showing_location_v1_users_showing_location_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  /** Read Users Me */
  read_users_me_v1_users_me__get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
}
