import { paths, components } from "./schema"; // <- generated by openapi-typescript


// Schema Obj
export type AuthRequest = components["schemas"]["AuthRequest"];
export type AuthResponse = components["schemas"]["AuthResponse"];
export type User = components["schemas"]["User"];
export type HTTPValidationError = components["schemas"]["HTTPValidationError"];
export type ValidationError = components["schemas"]["ValidationError"];


// // Path params
//type EndpointParams = paths["/v1/authm"]["post"]

// // Response obj
// type SuccessResponse = paths["/my/endpoint"]["get"]["responses"][200]["content"]["application/json"]["schema"];
// type ErrorResponse = paths["/my/endpoint"]["get"]["responses"][500]["content"]["application/json"]["schema"];
