import {components} from './schema'; // <- generated by openapi-typescript
/*
these types are based on the openapi schema of the api
new types can be generated by running the command
npx openapi-typescript http://{{api-url}}/openapi.json -o ./api_schema/schema.d.ts
*/

// Schema Obj
export type AuthRequest = components['schemas']['AuthRequest'];
export type AuthResponse = components['schemas']['AuthResponse'];
export type User = components['schemas']['User'];
export type UserEvent = components['schemas']['UserEvent'];
export type ExtendedUserEvent = components['schemas']['ExtendedUserEvent'];
export type UserUpdate = components["schemas"]["UserUpdate"];
export type UserLocation = components["schemas"]["UserLocation"];
export type ExternalEvent = components["schemas"]["ExternalEvent"];
export type HTTPValidationError = components["schemas"]["HTTPValidationError"];
export type ValidationError = components["schemas"]["ValidationError"];
