export const DEFAULT_SETTINGS = {
    // Location settings
    BACKGROUND_LOCATION_UPDATES: false,
    LOCATION_FILTER_HOURS: 8,
    LOCATION_UPDATE_INTERVAL_SECONDS: 60,
    MIN_LOCATION_UPDATE_SECONDS: 5,
    MAX_LOCATION_UPDATE_SECONDS: 120,

    // Events settings
    EVENTS_REFRESH_INTERVAL_SECONDS: 60,
    MIN_EVENTS_REFRESH_SECONDS: 10,
    MAX_EVENTS_REFRESH_SECONDS: 300,
} as const;