name: Build and Release Android App

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Set build version
        run: echo "BUILD_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create .env file
        working-directory: app
        run: |
          touch .env
          echo "API_URL=https://swag.mikael.green/api" >> .env
          echo "TEST_MODE=false" >> .env

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install npm dependencies
        working-directory: app
        run: npm install

      - name: Build Android App Bundle
        working-directory: app/android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease --no-daemon -PversionName=${{ inputs.version }}

      - name: Sign App APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Signed App APK
          path: app/android/app/build/outputs/apk/release/app-release.apk

      - name: Get Release
        id: get_release
        uses: joutvhu/get-release@v1
        with:
          tag_name: ${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./app/android/app/build/outputs/apk/release/app-release-unsigned-signed.apk
          asset_name: swag-app-${{ inputs.version  }}.apk
          asset_content_type: application/vnd.android.package-archive
