name: Build and Release Android App

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Set build version
        run: echo "BUILD_VERSION=$(date +%Y.%m.%d)-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Extract Date from Tag
        id: date_extract
        run: |
          TAG_NAME="${GITHUB_REF##*/}"
          RELEASE_DATE=$(echo $TAG_NAME | sed -e 's/Release //')
          echo "RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_ENV

      - name: Create .env file
        working-directory: app
        run: |
          touch .env
          echo "API_URL=https://swag.mikael.green/api" >> .env
          echo "TEST_MODE=false" >> .env

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install npm dependencies
        working-directory: app
        run: npm install

      - name: Build Android App Bundle
        working-directory: app/android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease --no-daemon -PversionName=${{ inputs.version }}

      - name: Sign App APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Signed App APK
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: Release ${{ inputs.version }}
          release_name: Release ${{ inputs.version  }}
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./android/app/build/outputs/apk/release/app-release-unsigned-signed.apk
          asset_name: swag-app-${{ inputs.version  }}.apk
          asset_content_type: application/vnd.android.package-archive
