name: Update GitOps with new image tags - app verification version

on:
  workflow_dispatch:

jobs:
  push-to-repo-B:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo-A
        uses: actions/checkout@v3

      - name: Generate GitHub App Installation Token
        uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.GITOPS_APP_ID }}
          private_key: ${{ secrets.GITOPS_APP_PRIVATE_KEY }}

      - name: Clone and print target repo contents for verification
        run: |
          git clone https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/mensasverige/swagapp-ops.git
          cd swagapp-ops
          ls -la